version: '3.8'

services:
  # Container 1: Your custom backend engine
  web-backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - local-db

  # Container 2: A ready-made PostgreSQL Database
  local-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: pratik
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: factory_data
    ports:
      - "5432:5432"